add ability to deploy log-cache colocated with dopplers
[#154735537]

diff --git a/scripts/generate-deploy-in-cf-ops b/scripts/generate-deploy-in-cf-ops
--- a/scripts/generate-deploy-in-cf-ops
+++ b/scripts/generate-deploy-in-cf-ops
@@ -4,6 +4,18 @@ set -eu
 
 trap "echo Exited!; exit 1;" SIGINT SIGTERM
 
+colocate_with_dopple=false
+while getopts ":c" opt; do
+  case $opt in
+    c)
+      colocate_with_doppler=true
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      ;;
+  esac
+done
+
 PROJECT_DIR="$(cd "$(dirname "$0")/.."; pwd)"
 cd $PROJECT_DIR
 
@@ -35,6 +47,34 @@ $(bosh int $tmp_dir/adjusted.yml --path /variables/name=$v | sed 's/^/    /')
 EOF
 done
 
+for j in $(bosh int $tmp_dir/adjusted.yml --path /instance_groups/name=log-cache/jobs | egrep '^- name' | awk '{print $3}')
+do
+cat <<EOF >> $tmp_dir/jobs.yml
+- type: replace
+  path: /instance_groups/name=doppler/jobs/-
+  value:
+$(bosh int $tmp_dir/adjusted.yml --path /instance_groups/name=log-cache/jobs/name=$j | sed 's/^/    /')
+EOF
+done
+
+if [ "$colocate_with_doppler" = true ]; then
+# write jobs to the doppler instance group
+cat <<EOF > manifests/operations/deploy-in-cf.yml
+# NOTE: This is generated code
+# The following operations file has been generated by the
+# scripts/generate_deploy_in_cf_ops script.
+# It is generated from the standalone manifest (manifests/log-cache.yml) and
+# altered to fit into the CF-Deployment manifest.
+
+- type: replace
+  path: /releases/-
+  value:
+    name: log-cache
+    version: latest
+$(cat $tmp_dir/jobs.yml)
+$(cat $tmp_dir/vars.yml)
+EOF
+else
 # write instance_groups and variables to new ops-file
 cat <<EOF > manifests/operations/deploy-in-cf.yml
 # NOTE: This is generated code
@@ -54,3 +94,4 @@ cat <<EOF > manifests/operations/deploy-in-cf.yml
 $instance_groups
 $(cat $tmp_dir/vars.yml)
 EOF
+fi
